=== Mariesnlk/XML-project/LabRegisterEX/registerEx.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="registerEX">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="man" minOccurs="0" maxOccurs="200">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="initials">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="([a-zA-Z\s]*){3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="status">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="ex"/>
                                        <xs:enumeration value="current"/>
                                        <xs:enumeration value="future"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="([0-9a-zA-Z]([-_.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-_\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="color_of_hair">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="blond"/>
                                        <xs:enumeration value="brown"/>
                                        <xs:enumeration value="black"/>
                                        <xs:enumeration value="ginger red"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="color_of_eyes">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="blue"/>
                                        <xs:enumeration value="gray"/>
                                        <xs:enumeration value="green"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="height">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="55"/>
                                        <xs:maxInclusive value="280"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="orderid" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Mariesnlk/XML-project/LabRegisterEX/registerEx.xml
<?xml version="1.0"?>
<registerEX orderid="889923" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="registerEx.xsd">
    <man>
        <initials>Melnyk Oleksandr Andriyovych</initials>
        <status>ex</status>
        <email>melnykxxl@gmail.com</email>
        <color_of_hair>blond</color_of_hair>
        <color_of_eyes>blue</color_of_eyes>
        <height>182</height>
    </man>
    <man>
        <initials>Kovalenko Mykhailo Igorovich</initials>
        <status>ex</status>
        <email>mykhailo@gmail.com</email>
        <color_of_hair>blond</color_of_hair>
        <color_of_eyes>green</color_of_eyes>
        <height>185</height>
    </man>
    <man>
        <initials>Tkachenko Andrii Oleksiyovich</initials>
        <status>ex</status>
        <email>andrtkach@gmail.com</email>
        <color_of_hair>black</color_of_hair>
        <color_of_eyes>blue</color_of_eyes>
        <height>186</height>
    </man>
    <man>
        <initials>Kovalchuk Andrii Olegovich</initials>
        <status>current</status>
        <email>kovalchuchka@gmail.com</email>
        <color_of_hair>brown</color_of_hair>
        <color_of_eyes>green</color_of_eyes>
        <height>180</height>
    </man>
    <man>
        <initials>Koval Ihor Andriyovich</initials>
        <status>ex</status>
        <email>Koval_Ihor@gmail.com</email>
        <color_of_hair>blond</color_of_hair>
        <color_of_eyes>gray</color_of_eyes>
        <height>185</height>
    </man>
    <man>
        <initials>Oliinyk Oleg Sergitovich</initials>
        <status>future</status>
        <email>oleg.oliinykchek@gmail.com</email>
        <color_of_hair>blond</color_of_hair>
        <color_of_eyes>green</color_of_eyes>
        <height>179</height>
    </man>
    <man>
        <initials>Moroz Artem Vladuslavovich</initials>
        <status>future</status>
        <email>moroz.artem@gmail.com</email>
        <color_of_hair>brown</color_of_hair>
        <color_of_eyes>blue</color_of_eyes>
        <height>181</height>
    </man>
    <man>
        <initials>Kostiuk Illia Ruslanovych</initials>
        <status>future</status>
        <email>hi_welcom_home@ukr.net</email>
        <color_of_hair>black</color_of_hair>
        <color_of_eyes>blue</color_of_eyes>
        <height>179</height>
    </man>
    <man>
        <initials>Boiko Andrii Oleksandrovych</initials>
        <status>future</status>
        <email>andr.boiko@gmail.com</email>
        <color_of_hair>blond</color_of_hair>
        <color_of_eyes>gray</color_of_eyes>
        <height>181</height>
    </man>
</registerEX>
